name: vseschedule_03
description: A new Flutter application.

version: 1.0.2+2

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  logging: 0.11.4
  #DATABASE
  path_provider: ^1.6.5
  sqflite: any
  #CREDENTIAL STORE
  flutter_secure_storage: ^3.3.1+1
  #WEB
  http: any
  html: any

  #BLOCS
  rxdart: ^0.18.0


  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  #IMAGES
  assets:
    - images/login_pixel2_960.jpg
    - images/schedule_pixel2_960.jpg


  #FONTS
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
    - family: Quicksand
      fonts:
        - asset: fonts/quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: fonts/quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: fonts/quicksand/Quicksand-Medium.ttf
          weight: 500
