name: vseschedule_03
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:

  path: any
  path_provider: ^1.6.5
  flutter_secure_storage: ^3.3.1+1
  logging: 0.11.4
  http: any
  html: any
  rxdart: ^0.18.0
  google_fonts: ^0.3.10
  numberpicker: ^1.2.0
  flutter_swiper: ^1.1.6


  flutter:
    sdk: flutter
  sqflite: any




  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
      - images/login_pixel2.jpg
      - images/login_pixel2_960.jpg
      - images/login_pixel2_960_mirr.jpg
      - images/schedule_pixel2_960.jpg
      - images/schedule_pixel2_960_mirr.jpg

  fonts:
      - family: Poppins
        fonts:
          - asset: fonts/poppins/Poppins-Thin.ttf
            weight: 100
          - asset: fonts/poppins/Poppins-ExtraLight.ttf
            weight: 200
          - asset: fonts/poppins/Poppins-Light.ttf
            weight: 300
          - asset: fonts/poppins/Poppins-Regular.ttf
            weight : 400
          - asset: fonts/poppins/Poppins-Medium.ttf
            weight : 500
      - family: Quicksand
        fonts:
          - asset: fonts/quicksand/Quicksand-Light.ttf
            weight: 300
          - asset: fonts/quicksand/Quicksand-Regular.ttf
            weight: 400
          - asset: fonts/quicksand/Quicksand-Medium.ttf
            weight: 500
